### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by ghost** [TheAlexDev23/Terminal-Video-Player#1]
i have followed the instructions in the readme but when i run python ./Player.py video.mpv i got 

Traceback (most recent call last):
  File "/home/micro/Public/git-box/Terminal-Video-Player/Player.py", line 2, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by TheAlexDev23** [comment]
My program requires the python cv2 (OpenCV) and PIL (Pillow) libraries to run.
It seems, that you are missing the OpenCV python library.
Install it by running:
```bash
pip install opencv-python
```
If the same error but with the PIL module comes up, you would need to install the pillow library:
```bash
pip install pillow
```

**Comment by ghost** [comment]
installing opencv-python solved my issue thanks.
